import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import {Toaster} from 'sonner'

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { ThemeProvider } from "./_components/theme-provider";
import LandingPage from "./landing/page";

export const metadata: Metadata = {
  title: "Clarity",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/mintlify.svg" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (

    <ClerkProvider 
      afterSignOutUrl="/landing"
      signUpUrl="/sign-up"
      signInUrl="/sign-in"
    >
      <html lang="en" className={`${GeistSans.variable}`}>
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <TRPCReactProvider>
              {children}
            </TRPCReactProvider>
            <Toaster richColors/>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>

  );
}
